/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 head-final.glb ../../src/components/Models/ 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/head-final.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.closed_eyes.geometry} material={materials.texture} />
    </group>
  )
}

useGLTF.preload('/head-final.glb')
