export const tech = [
  {
    text: "React",
    imgPath: "/logos/react.svg",
    imgPathPNG: "/logos/react.png",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 4],
    position: [-3, 1.2, 3],
    color: "#00d5f6",
    description: "React, for the core of this app",
  },
  {
    text: "Linux",
    imgPath: "/logos/linux.svg",
    imgPathPNG: "/logos/linux.png",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [3, -1, 5],
    color: "#F0F0F0",
    description: "Linux, open-source and just better",
  },
  {
    text: "Docker",
    imgPath: "/logos/docker.svg",
    imgPathPNG: "/logos/docker.png",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 3],
    position: [3, 1.8, 5],
    color: "#009cf7",
    description: "Docker container",
  },
  {
    text: "HTML",
    imgPath: "/logos/html.svg",
    imgPathPNG: "/logos/html.png",
    heroRotation: [Math.PI / 8, Math.PI / -4, Math.PI / -4],
    position: [-1.1, -1.4, 2.7],
    color: "#f73c1c",
    description: "HTML for structure",
  },
  {
    text: "CSS",
    imgPath: "/logos/css.svg",
    imgPathPNG: "/logos/css.png",
    heroRotation: [Math.PI / 8, Math.PI / -3, Math.PI / -3],
    position: [-3, 2.5, -0.5],
    color: "#F0F0F0",
    description: "CSS for a small styling",
  },
  {
    text: "JavaScript",
    imgPath: "/logos/js.svg",
    imgPathPNG: "/logos/js.png",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [-3, 1.8, 5],
    color: "#f18615",
    description: "Its JavaScript description",
  },
  {
    text: "Git",
    imgPath: "/logos/git.svg",
    imgPathPNG: "/logos/git.png",
    heroRotation: [Math.PI / 3, Math.PI / 4, Math.PI / 8],
    position: [3.5, 2, 0],
    color: "#f73c1c",
    description: "Git for those times when i sended zip projects to my friend",
  },
  {
    text: "Tailwind",
    imgPath: "/logos/tailwind.svg",
    imgPathPNG: "/logos/tailwind.png",
    heroRotation: [Math.PI / 8, Math.PI / 3, Math.PI / 4],
    position: [-3, -1, 5],
    color: "#F0F0F0",
    description: "Tailwind = styling",
  },
  {
    text: "Github",
    imgPath: "/logos/github.svg",
    imgPathPNG: "/logos/github.png",
    heroRotation: [Math.PI / 3, Math.PI / 4, Math.PI / 8],
    position: [1.6, 1.35, 0],
    color: "#373737",
    description: "Github to flex",
  },
  {
    text: "Postgresql",
    imgPath: "/logos/postgresql.png",
    imgPathPNG: "/logos/postgresql.png",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [-1, 2.5, 0],
    color: "#7fd03e",
    description: "Postgresql - scalability",
  },
  {
    text: "MongoDB",
    imgPath: "/logos/mongodb.svg",
    imgPathPNG: "/logos/mongodb.svg",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [2, 2.5, 0],
    color: "#023530",
    description: "MongoDB - DB for everyone",
  },
  {
    text: "Python",
    imgPath: "/logos/python.svg",
    imgPathPNG: "/logos/python.svg",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [1.7, -1.4, 2.2],
    color: "#f8c325",
    description: "Pythn for all most of large data managment",
  },
  {
    text: "Kubernetes",
    imgPath: "/logos/kubernetes.svg",
    imgPathPNG: "/logos/kubernetes.svg",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [2, 0.2, 1.5],
    color: "#2e6ce6",
    description: "Kubernetes, to contain the containers",
  },
  {
    text: "Go",
    imgPath: "/logos/golang.svg",
    imgPathPNG: "/logos/golang.svg",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [3, -0.6, 2.5],
    color: "#2e6ce6",
    description: "Go - fast, compilable, beast",
  },
  {
    text: "NeoVim",
    imgPath: "/logos/neovim.svg",
    imgPathPNG: "/logos/neovim.svg",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [-3, -0.6, 2.5],
    color: "#089d37",
    description: "NeoVim unlocks full potantial of my laptop",
  },
];

export const navLinks = [
  {
    name: "Work",
    link: "#work",
  },
  {
    name: "Experience",
    link: "#Experience",
  },
  {
    name: "Skills",
    link: "#Skills",
  },
  {
    name: "GitHub",
    link: "https://github.com/Vladicki",
  },
];
