export const tech = [
  {
    text: "React",
    imgPath: "/logos/react.svg",
    imgPathPNG: "/logos/react.png",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 4],
    position: [-3, 1.2, 3],
    padPosition: [0, 0, 0],
    color: "#00d5f6",
    description: "React, for the core of this app",
  },
  {
    text: "Docker",
    imgPath: "/logos/docker.svg",
    imgPathPNG: "/logos/docker.png",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 3],
    position: [3, 1.8, 5],
    padPosition: [2, 0, 0],
    color: "#009cf7",
    description: "Docker container",
  },
  {
    text: "Python",
    imgPath: "/logos/python.svg",
    imgPathPNG: "/logos/python.svg",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [1.7, -1.4, 2.2],
    padPosition: [1, 0, 0],
    color: "#f8c325",
    description: "Pythn for all most of large data managment",
  },
  {
    text: "HTML",
    imgPath: "/logos/html.svg",
    imgPathPNG: "/logos/html.png",
    heroRotation: [Math.PI / 8, Math.PI / -4, Math.PI / -4],
    position: [-1.1, -1.4, 2.7],
    padPosition: [-1, 0, 0],
    color: "#f73c1c",
    description: "HTML for structure",
  },
  {
    text: "CSS",
    imgPath: "/logos/css.svg",
    imgPathPNG: "/logos/css.png",
    heroRotation: [Math.PI / 8, Math.PI / -3, Math.PI / -3],
    position: [-3, 2.5, -0.5],
    padPosition: [-2, 0, 0],
    color: "#F0F0F0",
    description: "CSS for a small styling",
  },
  {
    text: "JavaScript",
    imgPath: "/logos/js.svg",
    imgPathPNG: "/logos/js.png",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [-3, 1.8, 5],
    padPosition: [-3, 0, 0],
    color: "#f18615",
    description: "Its JavaScript description",
  },
  {
    text: "Linux",
    imgPath: "/logos/linux.svg",
    imgPathPNG: "/logos/linux.png",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [3, -1, 5],
    padPosition: [2, 0, -1],
    color: "#F0F0F0",
    description: "Linux, open-source and just better",
  },
  {
    text: "MongoDB",
    imgPath: "/logos/mongodb.svg",
    imgPathPNG: "/logos/mongodb.svg",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [2, 2.5, 0],
    padPosition: [1, 0, -1],
    color: "#023530",
    description: "MongoDB - DB for everyone",
  },
  {
    text: "NodeJS",
    imgPath: "/logos/node.svg",
    imgPathPNG: "/logos/node.svg",
    heroRotation: [Math.PI / 3, Math.PI / 4, Math.PI / 8],
    position: [1.6, 1.35, 0],
    padPosition: [-2, 0, -1],
    color: "#f19733",
    description: "Nodejs",
  },
  {
    text: "Git",
    imgPath: "/logos/git.svg",
    imgPathPNG: "/logos/git.png",
    heroRotation: [Math.PI / 3, Math.PI / 4, Math.PI / 8],
    position: [3.5, 2, 0],
    padPosition: [0, 0, -1],
    color: "#f73c1c",
    description: "Git for those times when i sended zip projects to my friend",
  },
  {
    text: "Tailwind",
    imgPath: "/logos/tailwind.svg",
    imgPathPNG: "/logos/tailwind.png",
    heroRotation: [Math.PI / 8, Math.PI / 3, Math.PI / 4],
    position: [-3, -1, 5],
    padPosition: [-3, 0, -2],
    color: "#F0F0F0",
    description: "Tailwind = styling",
  },
  {
    text: "Github",
    imgPath: "/logos/github.svg",
    imgPathPNG: "/logos/github.png",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [1.4, -0.6, 1.5],
    padPosition: [1, 0, -2],
    color: "#373737",
    description: "Github to flex",
  },
  {
    text: "Postgresql",
    imgPath: "/logos/postgresql.png",
    imgPathPNG: "/logos/postgresql.png",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [-1, 2.5, 0],
    padPosition: [-1, 0, -1],
    color: "#7fd03e",
    description: "Postgresql - scalability",
  },
  {
    text: "Kubernetes",
    imgPath: "/logos/kubernetes.svg",
    imgPathPNG: "/logos/kubernetes.svg",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [2, 0.2, 1.5],
    padPosition: [0, 0, -2],
    color: "#2e6ce6",
    description: "Kubernetes, to contain the containers",
  },
  {
    text: "NeoVim",
    imgPath: "/logos/neovim.svg",
    imgPathPNG: "/logos/neovim.svg",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [-3, -0.6, 2.5],
    padPosition: [-3, 0, -1],
    color: "#089d37",
    description: "NeoVim unlocks full potantial of my laptop",
  },
  {
    text: "Go",
    imgPath: "/logos/golang.svg",
    imgPathPNG: "/logos/golang.svg",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [3, -0.6, 2.5],
    padPosition: [2, 0, -2],
    color: "#2e6ce6",
    description: "Go - fast, compilable, beast",
  },
  {
    text: "ThreeJS",
    imgPath: "/logos/three.png",
    imgPathPNG: "/logos/three.png",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [-2, -0.9, 1],
    padPosition: [-2, 0, -2],
    color: "#089d37",
    description: "ThreeJs for the 3D ~MAGIC~",
  },
  {
    text: "Java",
    imgPath: "/logos/java.svg",
    imgPathPNG: "/logos/java.svg",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [-2, 1.3, 1],
    padPosition: [-1, 0, -2],
    color: "#f19733",
    description: "Java, why uni dont teach Python?",
  },
];

export const navLinks = [
  {
    name: "Experience",
    link: "#Experience",
  },
  {
    name: "Work",
    link: "#work",
  },
  {
    name: "Skills",
    link: "#Skills",
  },
  {
    name: "GitHub",
    link: "https://github.com/Vladicki",
  },
];

export const socialImgs = [
  {
    name: "insta",
    imgPath: "/socials/insta.png",
  },
  {
    name: "gh",
    imgPath: "/socials/github.png",
  },
  {
    name: "linkedin",
    imgPath: "/socials/linkedin.png",
  },
];

export const experiences = [
  {
    title: "ThreeJS Web CV",
    stack: [
      { tech: "React", tailwindColor: "#00d5f6", textColor: "#0F0F0F" }, // Use the named color
      { tech: "ThreeJS", tailwindColor: "#0F0F0F" }, // Or map to an existing tech color
      { tech: "Tailwind", tailwindColor: "#089d37", textColor: "#0F0F0F" },
      { tech: "Git", tailwindColor: "#f19733", textColor: "#0F0F0F" }, // Use the named color
    ],
    desc: "Developed a high-end interactive CV website using React, Vite, Three.js, and GSAP. Designed modular, scalable architecture, integrated 3D models with advanced lighting, and delivered Awwwards-level animations. Managed responsive design with Tailwind CSS and version control with Git/GitHub.",
  },
  {
    title: "Python-Go",
    stack: [
      { tech: "Python", tailwindColor: "#00d5f6", textColor: "#0F0F0F" }, // Use the named color
      { tech: "OOP", tailwindColor: "#0F0F0F" }, // Or map to an existing tech color
      { tech: "Git", tailwindColor: "#089d37", textColor: "#0F0F0F" },
      { tech: "GitHub", tailwindColor: "#f19733", textColor: "#0F0F0F" }, // Use the named color
    ],
    desc: "Led the end-to-end development of a fully interactive Go game using Python and Qt6. Designed scalable OOP architecture, implemented responsive UI, and integrated robust scoring logic. Collaborated via Git for version control.",
  },
  {
    title: "Guy Hawkins",
    stack: ["@guyhawkins"],
    desc: "Developed a high-end interactive CV website using React, Vite, Three.js, and GSAP. Designed modular, scalable architecture, integrated 3D models with advanced lighting, and delivered Awwwards-level animations. Managed responsive design with Tailwind CSS and version control with Git/GitHub.",
  },
  {
    title: "Marvin McKinney",
    stack: ["@marvinmckinney"],
    desc: "Developed a high-end interactive CV website using React, Vite, Three.js, and GSAP. Designed modular, scalable architecture, integrated 3D models with advanced lighting, and delivered Awwwards-level animations. Managed responsive design with Tailwind CSS and version control with Git/GitHub.",
  },
  {
    title: "Floyd Miles",
    stack: ["@floydmiles"],
    desc: "Developed a high-end interactive CV website using React, Vite, Three.js, and GSAP. Designed modular, scalable architecture, integrated 3D models with advanced lighting, and delivered Awwwards-level animations. Managed responsive design with Tailwind CSS and version control with Git/GitHub.",
  },
  {
    title: "Albert Flores",
    stack: ["@albertflores"],
    desc: "Developed a high-end interactive CV website using React, Vite, Three.js, and GSAP. Designed modular, scalable architecture, integrated 3D models with advanced lighting, and delivered Awwwards-level animations. Managed responsive design with Tailwind CSS and version control with Git/GitHub.",
  },
];

export const expCards = [
  {
    desc: "Vladick built solid fundamentals in Computer Science and quickly applied them in practical projects, showcasing both theory and application.",
    imgPath: "/logos/graduation-cap.svg",
    logoPath: "/logos/graduation-cap.svg",
    title: "BSc Computer Science Student – Griffith College",
    date: "2022 – Present",
    responsibilities: [
      "Learned core Java programming, mastering data structures, algorithms, and OOP principles.",
      "Developed fundamental projects demonstrating problem-solving and clean code practices.",
      "Gained exposure to databases, SQL queries, and full-stack development basics.",
    ],
  },
  {
    desc: "With strong problem-solving ability, Vladislav took ownership of DevOps and Cybersecurity foundations, enhancing both infrastructure and security practices.",
    imgPath: "/logos/linux.svg",
    logoPath: "/logos/linux.svg",
    title: "DevOps & Cybersecurity Enthusiast",
    date: "2024 – 2025",
    responsibilities: [
      "Administered Linux-based systems (Arch + Hyprland), optimizing performance and security.",
      "Implemented GPU switching (AMD iGPU + NVIDIA dGPU) to improve power efficiency and workflows.",
      "Initiated DevOps practices, learning containerization, process monitoring, and automation.",
      "Explored cybersecurity fundamentals, including networking, encryption, and system hardening.",
    ],
  },
  {
    desc: "Vladick demonstrated exceptional creativity and technical mastery, delivering a cutting-edge interactive CV that rivaled award-winning portfolios. His ability to combine 3D graphics with performant web architecture was outstanding.",
    imgPath: "/logos/react.svg",
    logoPath: "/logos/react.svg",
    title: "Freelance Frontend / Creative Developer",
    date: "2024 – 2025",
    responsibilities: [
      "Developed a high-end interactive CV website using React, Vite, Three.js, and GSAP with advanced animations and modular architecture.",
      "Designed responsive UI with Tailwind CSS, ensuring cross-device optimization and seamless user experiences.",
      "Integrated 3D models, lighting, and motion design that achieved an Awwwards-level portfolio standard.",
      "Managed version control with Git/GitHub, enforcing best practices in commits and branching strategies.",
    ],
  },
];
