export const tech = [
  {
    text: "React",
    imgPath: "/logos/react.svg",
    imgPathPNG: "/logos/react.png",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 4],
    position: [-3, 0, -3],
    color: "#00d5f6",
    description: "Its React description",
  },
  {
    text: "Linux",
    imgPath: "/logos/linux.svg",
    imgPathPNG: "/logos/linux.png",
    heroRotation: [Math.PI / 8, Math.PI / -4, Math.PI / -4],
    position: [3, 0, -3],
    color: "#F0F0F0",
    description: "Its Linux description",
  },
  {
    text: "Docker",
    imgPath: "/logos/docker.svg",
    imgPathPNG: "/logos/docker.png",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 3],
    position: [3, 1.8, 5],
    color: "#009cf7",
    description: "Its Docker description",
  },
  {
    text: "HTML",
    imgPath: "/logos/html.svg",
    imgPathPNG: "/logos/html.png",
    heroRotation: [Math.PI / 8, Math.PI / 4, Math.PI / 4],
    position: [3, -1, 5],
    color: "#f73c1c",
    description: "Its HTML description",
  },
  {
    text: "CSS",
    imgPath: "/logos/css.svg",
    imgPathPNG: "/logos/css.png",
    heroRotation: [Math.PI / 8, Math.PI / -3, Math.PI / -3],
    position: [-3, 2.5, -3],
    color: "#F0F0F0",
    description: "Its CSS description",
  },
  {
    text: "JavaScript",
    imgPath: "/logos/js.svg",
    imgPathPNG: "/logos/js.png",
    heroRotation: [Math.PI / 3, Math.PI, Math.PI / 7],
    position: [-3, 1.8, 5],
    color: "#f18615",
    description: "Its JavaScript description",
  },
  {
    text: "Git",
    imgPath: "/logos/git.svg",
    imgPathPNG: "/logos/git.png",
    heroRotation: [Math.PI / 3, Math.PI / 4, Math.PI / 8],
    position: [3, 1.8, -3],
    color: "#f73c1c",
    description: "Its Git description",
  },
  {
    text: "Tailwind",
    imgPath: "/logos/tailwind.svg",
    imgPathPNG: "/logos/tailwind.png",
    heroRotation: [Math.PI / 8, Math.PI / 3, Math.PI / 4],
    position: [-3, -1, 5],
    color: "#F0F0F0",
    description: "Its Tailwind description",
  },
  {
    text: "Github",
    imgPath: "/logos/github.svg",
    imgPathPNG: "/logos/github.png",
    heroRotation: [Math.PI / 3, Math.PI / 4, Math.PI / 8],
    position: [3, 0.8, -3],
    color: "#373737",
    description: "Its Github description",
  },
];

export const quote = [
  { text: "If only there were an employee" },
  { text: "God, the WORk, sounds good" },
  { text: "If only they knew how good my promts are" },
  { text: "Should've said i use Arch" },
  { text: "Why spinning donuts, can secure a job position" },
];
export const navLinks = [
  {
    name: "Work",
    link: "#work",
  },
  {
    name: "Experience",
    link: "#Experience",
  },
  {
    name: "Skills",
    link: "#Skills",
  },
  {
    name: "GitHub",
    link: "https://github.com/Vladicki",
  },
];
