/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 donut.glb paper_plane.glb knot.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Donut(props) {
  const { nodes, materials } = useGLTF('models/donut.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} />
    </group>
  )
}

useGLTF.preload('models/donut.glb')
