/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 head-final.glb ../../src/components/Models/ 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { Decal, Float, Preload, useTexture } from '@react-three/drei'
export function Head_final(props) {

    const [decalTexture] = useTexture("../../../public/models/eyes_closed.png")
    const { nodes, materials } = useGLTF('/models/head-final.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.closed_eyes.geometry} material={materials.texture} />


            <Decal
                //fixed bleed through
                transparent
                depthTest={true}
                depthWrite={true}
                debug // Makes "bounding box" of the decal visible
                position={[0, 0.9, 0]}     // adjust decal position (y+ is up)
                rotation={[Math.PI / 2, Math.PI, 0,]}         // adjust decal rotation
                scale={1}                  // adjust decal size
                polygonOffset
                polygonOffsetFactor={-4}
                map={decalTexture}
                flatShading
            />
        </group>
    )
}

useGLTF.preload('/models/head-final.glb')


