/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 head-textured.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Head_outdated(props) {
    const { nodes, materials } = useGLTF('/models/head-textured.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.FBHead.geometry} material={materials.chat} />
        </group>
    )
}

useGLTF.preload('/models/head-textured.glb')
