/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 keyboard-base-xl.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function KeyboardBase({ baseColor = "#444444", ...props }) { // Added baseColor prop with default
    const { nodes } = useGLTF('/models/keyboard.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.aMain.geometry}
                scale={[4, 0.2, 7.8]}
                rotation={[0, Math.PI / 2, 0]}
                position={[-1.25, -2, -2.5]}
            >
                <meshStandardMaterial color={baseColor} roughness={0.2} metalness={0.8} /> {/* Using baseColor here */}
            </mesh>
        </group>
    )
}

useGLTF.preload('models/keyboard.glb')
