/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 keyboard-base-xl.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function KeyboardBase(props) {
    const { nodes, materials } = useGLTF('/models/keyboard.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.aMain.geometry}
                // material={nodes.aMain.material}
                scale={[4, 0.2, 7.8]}
                rotation={[0, Math.PI / 2, 0]}
                position={[-1.25, -2, -2.5]}


            >
                <meshStandardMaterial color="black" roughness={0.5} metalness={0.4} />
            </mesh>
        </group>
    )
}

useGLTF.preload('models/keyboard.glb')
