/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 knot.glb 
Author: crespi.f (https://sketchfab.com/crespi.f)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-torus-knot-112-b27565abd473485c9cdb48ea1d745760
Title: Lowpoly torus knot 11,2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Knot(props) {
  const { nodes, materials } = useGLTF('models/knot.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.None} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/knot.glb')
