/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 monke.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Monke(props) {
    const { nodes, materials } = useGLTF('/models/monke.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} />
        </group>
    )
}

useGLTF.preload('/monke.glb')
