/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 paper_plane.glb 
Author: LittleZCoordinate (https://sketchfab.com/LittleZCoordinate)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-plane-low-poly-game-ready-for-free-53c935434bbd4d398bed826b0dd07446
Title: Paper Plane - Low Poly Game Ready For Free
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Plane(props) {
  const { nodes, materials } = useGLTF('models/paper_plane.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.118}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.PaperPlane__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/paper_plane.glb')
